[package]
name = "bevy_quinnet_breakout"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11.0"
bevy_quinnet = "0.5.0"
serde = "1.0.171"

[[bin]]
name = "breakout"
path = "src/breakout.rs"
