[package]
name = "wgpu-wasm-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
gloo-console = "0.2.3"
instant = { version = "0.1", features = ["wasm-bindgen", "inaccurate"] }
js-sys = "0.3.60"
serde-wasm-bindgen = "0.4.5"
serde_json = "1.0.89"
wasm-bindgen = "0.2.83"
