[package]
name = "wgpu-wasm-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.14"
pollster = "0.2"
gloo-console = "0.2.3"
bytemuck = { version = "1.4", features = ["derive"] }
instant = { version = "0.1", features = ["wasm-bindgen", "inaccurate"] }
anyhow = "1.0.66"
wgpu_glyph = "0.18.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
wgpu = { version = "0.14", features = ["webgl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "HtmlHeadElement",
    "CssStyleDeclaration",
    "DomRect",
    "HtmlCanvasElement",
    "EventTarget",
    "MouseEvent",
    "WheelEvent"
] }
